const numbers: number[] = [1 ,2 ,3, 4];
console.log("Step 1: Create an array of numbers. Use the '.map' function to double all the numbers in the array.");
console.log(numbers.map((num: number) => num * 2));
const words: string[] = ['one', 'two', 'three'];
console.log("Step 2: Create an array of words. Use the '.filter' function to select only the words that are longer than 3 letters.");
console.log(words.filter((word: string) => word.length > 3));
console.log("Step 3: Create an array of numbers. Use the '.reduce' function to calculate the sum of all the numbers in the array.");
console.log(numbers.reduce((acc: number, value: number) => acc + value));
console.log("Step 4: Create an array of numbers. Use the '.some' function to check if at least one number is greater than 10.");
console.log(numbers.some((value: number) => 10 < value));
